version: "3.8"

services:

  postgres:
    image: postgres:16

    container_name: customer_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_analytics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  airflow:
    build: .

    container_name: customer_airflow

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/customer_analytics

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_analytics

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./customer_analytics_dbt:/opt/customer_analytics_dbt
      - ./data:/opt/airflow/data

    command:
      airflow standalone

api:

  build:
    context: ./api

  container_name:
    churn_api

  ports:
    - "8000:8000"

  volumes:
    - ./ml:/app/ml
volumes:
  postgres_data: